spring:
  devtools:
     restart:
        enabled: true
        additional-exclude: s
        additional-paths: s
        trigger-file: s
     remote:
        debug:
           local-port: 8081
server:
   port: 80
spring:
  data:
    mongodb:
      uri: mongodb://princeandbeauty.com:27017/test